apiVersion: v1
kind: Secret
metadata:
  name: ghcr-cred
  namespace: homelab-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJiV0Z5YTJKbGJtcGhiV2x1YTJGMFlXMWlZVHBuYUhCZllqazBiemc1VTBkcFNGWkVTR0pCY1dkVWNsZ3dWVVZRUlhoV2VWRjBNVXRUWm5CQyINCiAgICB9DQogIH0NCn0=
