# This file helps to dynamically override the image tag for the taskflow-backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
spec:
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
    spec:
      containers:
        - name: taskflow-backend
          image: ghcr.io/markbenjaminkatamba/taskflow-backend-dev:main-16664d8abacb0f3c67e4e70abebeeaeed5d1c6d3


