# This file helps to dynamically override the image tag for the taskflow-frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
spec:
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
        - name: taskflow-frontend
          image: ghcr.io/markbenjaminkatamba/taskflow-frontend-dev:main-16664d8abacb0f3c67e4e70abebeeaeed5d1c6d3


