# This file helps to dynamically override the image tag for the sukuulu deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sukuulu
spec:
  selector:
    matchLabels:
      app: sukuulu
  template:
    metadata:
      labels:
        app: sukuulu
    spec:
      containers:
        - name: sukuulu
          image: ghcr.io/markbenjaminkatamba/sukuulu:main-91d1725131535fb05ffee912580d258d7a6daf7a


