# This file helps to dynamically override the image tag for the sukuulu deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sukuulu
spec:
  selector:
    matchLabels:
      app: sukuulu
  template:
    metadata:
      labels:
        app: sukuulu
    spec:
      containers:
        - name: sukuulu
          image: ghcr.io/markbenjaminkatamba/sukuulu:main-f2875309bd01f295750331c767f7234aa379c5a5


