# This file helps to dynamically override the image tag for the dockerfile-generator-backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerfile-generator-backend
spec:
  selector:
    matchLabels:
      app: dockerfile-generator-backend
  template:
    metadata:
      labels:
        app: dockerfile-generator-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/markbenjaminkatamba/dockerfile-generator-backend-dev:develop-e9f3bad5eeae485f0dd09a37ce86cad271f1a996
