apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dockerfile-generator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  project: default
  source:
    path: homelab-gitops/apps/dockerfile-generator
    repoURL: https://github.com/MarkBenjaminKatamba/homelab-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
