apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bulungi-website
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-dev
  project: default
  source:
    path: apps/overlays/homelab-dev/bulungi-website
    repoURL: https://github.com/MarkBenjaminKatamba/bulungi-bespoke-showcase.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true


